### ISSUE TITLE
How to get the files in /data/keys/ folder?

### ISSUE THREAD

**Issue by caiyingchun** [WonhoZhung/DeepICL#4]
Hello, thanks for your nice tools. I want to reproduce your work and am going to run you script. I re-download the PDBBind databse and run ```preprocessing.py``` to get the processed pdb files. But how to get the files in ```/data/keys/``` folder? Is there a script avaliable? Thanks very much!

**Comment by WonhoZhung** [comment]
Did you mean the script to split train/validation/test?

**Comment by caiyingchun** [comment]
> Did you mean the script to split train/validation/test?

Yes, I wonder how to split train/validation/test?

**Comment by WonhoZhung** [comment]
I clustered the amino acid sequences of PDBbind general set by cd-hit software with 60% cutoff so that no sequences from distinct clusters have larger than 60% similarity. 
 `cd-hit -i {FASTA_FILENAME} -o {OUTPUT_NAME} -c 0.6 -n 3`
Clusters were then sorted with their sizes and distributed to each set with 8:1:1 ratio.

**Comment by caiyingchun** [comment]
Get it!. Thanks for your help.
